 import img2 from '../../ecommerce-app/src/assets/img2.jpg'
 import img3 from '../../ecommerce-app/src/assets/img3.jpg'
 import img4 from '../../ecommerce-app/src/assets/img4.jpg'
 import man1 from '../../ecommerce-app/src/assets/man1.jpg'
 import img2 from '../../ecommerce-app/src/assets/img2.jpg'
 import img2 from '../../ecommerce-app/src/assets/img2.jpg'
 import img2 from '../../ecommerce-app/src/assets/img2.jpg'
 import img2 from '../../ecommerce-app/src/assets/img2.jpg'
 import img2 from '../../ecommerce-app/src/assets/img2.jpg'
 import img2 from '../../ecommerce-app/src/assets/img2.jpg'
 import img2 from '../../ecommerce-app/src/assets/img2.jpg'
 import img2 from '../../ecommerce-app/src/assets/img2.jpg'
 import img2 from '../../ecommerce-app/src/assets/img2.jpg'
 import img2 from '../../ecommerce-app/src/assets/img2.jpg'
 import img2 from '../../ecommerce-app/src/assets/img2.jpg'
 import img2 from '../../ecommerce-app/src/assets/img2.jpg'
 import img2 from '../../ecommerce-app/src/assets/img2.jpg'

 export {img2,}